default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: cap_study_development
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: cap_study_production
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: cap_study_test

preview:
  <<: *default
  database: cap_study_test
