# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b009571d6afde9d56c4f823db7123cc5a816d96cc44a66ab40e6b79f158bccd49115695a28a388d8d59f2e9c3af31edd0cfb79771676260a7b7d3e2ed30714de

test:
  secret_key_base: 6703ae2e9cf180adbf48947b67773f2a5518bb050ad56c2f961354ec2fa47121a51866e8165b70babcd187a9f9bf0a958222420e613b64aa438c043e1863257c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
